### PR TITLE
Youtube index

### PR DESCRIPTION
**Pull request by yirano**

### CODE REVIEW

**Review by Redvanisation — CHANGES_REQUESTED** [review]
### Hello @yirano and @ferreirati  🌟 

### Great job on that project I really like your work, however before we move on we should do some small improvements:

1. Please **fix all the HTML validation errors**: https://validator.w3.org/#validate_by_input

2. **Update the README file** to be more descriptive, here is an example for inspiration: https://github.com/Redvanisation/microverse-bubble-sort

**[OPTIONAL]** - In HTML5 **self-closing tags omit the forward-slash** at the end "/" you could implement that if you want.

**[OPTIONAL]** - In order for your code to be more semantic you could use the:
- `<nav>` tag for the major navigation links.
- `<main>` tag for the dominant content of the `<body>` of a document.
- `<footer>` tag for the footer

###  _After making the required changes please submit a new code review request_

### **Goodluck Guys!** 🍀

**Comment by tiagoit** [comment]
Hello @Redvanisation, thankyou for the code review, we believe everithing is now fixed. We have opened a new PR.

**Review by uche-inyama — COMMENTED** [review]
## Pull request under review by: Inyama, Uchechukwu Henry

**Review by uche-inyama — CHANGES_REQUESTED** [review]
Hello team, nice, you have implemented all the changes.

But there is one update to implement, I believe my colleague missed it.
 - [x] There are not linter checks, on this project. Please, add a .stickler.yml file at the root of the project directory. Use this link as a guide [Set up a code linter](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/) If you have not signup on [Stickler](stickler-ci.com), please do so.

 #### I also made some observations:
- [**Note**] I can see you have merged two branches :smile: you do not merge a branch until it is approved, **one branch is fine**. Read up on [ Github Flow guidelines.](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/) 
- [x] Edit your README.md, remove the last two words **```for microverse```**. or as a suggestion, write **``` a Microverse Project```**  after the removing the words :+1: 

####  Configure your ```.stickler.yml```  and ensure your project passes the linter checks. After the implementation, submit another form for code review :muscle: 

#### Please reach out to me on Slack if you need clarifications @Inyama, Uchechukwu Henry.
### This project is not approved :stop_sign:

**Comment by tiagoit** [comment]
Hello @uche-inyama, tks for the code review, we have implemented all the suggestions.

**Review by stratospherique — APPROVED** [review]
### Great work :clap: . You made all the necessary changes :100: . You project is approved and you can merge to master :+1: :+1:

**Pull request merged**
